### ISSUE TITLE
A break problem

### ISSUE THREAD

**Issue by wwj-go** [panuph/httpcpp#1]
![image](https://user-images.githubusercontent.com/22536326/39669466-2fa7de2c-511f-11e8-9509-49258626e0e7.png)

  Here if the request  is NULL ,it means the content from client has  not been completed，we should continue to invoke read() function to read or register the fd with EPOLLIN to epoll again instead of simply break , I think it will cause an unexpected result . Am I right?
   The above is my opinion, look forward to your reply

**Comment by panuph** [comment]
The break is required to get out of the infinity (while) loop because no more data is available from the file descriptor (socket). Once the data is available, this on_read() method will be called again because we have not removed the file descriptor from epoll.

This code base lacks unit test cases, including the case you have queried, and they would make things a lot clearer to others -- I am sorry I did not do that.

**Comment by wwj-go** [comment]
I am sorry ，I have misunderstood the EPOLLET . At the beginning，I think for a fd the kernel will just notify once if the fd is registered with EPOLLET, now I have understand that if new data is coming we still are notified unless we  remove the fd from the epoll. 

In short, I understand it better. Thank you for your patience.
